//"1"
alert('Oleksandr');



//"2"
console.log('Kozak');



//"3"
let Age = 27;
let Name = 'Oleksandr';
alert(Age + ' ' + Name);
Age = Name ;
alert(Age + ' ' + Name);



//"4"
let User = {
    name: "Sasha",
    age: 29,
    info: null,
    newInfo: undefined,
    UA: true,
};



//"5"
const IsAdult = confirm("Are you of legal age?");
console.log(IsAdult);


//"6"
let MyName = "Sasha";
let SurName = "Kozak";
let StudyGroup = "UA.1019"
let Year = 1996;
let IsMarried = false;
console.log(typeof MyName);
console.log(typeof SurName);
console.log(typeof StudyGroup);
console.log(typeof Year);
console.log(typeof IsMarried);
console.log(Year+" "+MyName+" "+SurName+" "+StudyGroup);
let First = null;
let Second = undefined;
console.log(First +" "+Second);





//"7"
const Login = prompt("Login?");
alert(Login);

const Email = prompt("Email?");
alert(Email);

const PassWord = prompt("Password?");
alert(PassWord);

alert("Dear Sasha, your login is"+" "+Login +",your email is"+" "+Email +",your password is "+PassWord);






//"8"
let Second1 = 1;
let InHour = 60*60;
let PerDay = InHour * 24; 
let PerMounth = PerDay * 30; 
alert(InHour);
alert(PerDay);
alert(PerMounth);







